//! Parameter identifiers (stable string names are used by the JS API).

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PartParam {
    Volume,
    Pan,
    ReverbSend,
    Brightness,
    EvenDb,
    NoiseDb,
    AttackScale,
    DecayScale,
    ReleaseScale,
    VibratoCents,
    VibratoRate,
    VibratoDelay,
    Expression,
    Formant,
    Inharmonicity,
    Spread,
    Humanize,
    VelocitySens,
    MaxPartials,
    GainDb,
    Jitter,
    Shimmer,
    Transpose,
    Tune,
    BendRange,
    ModDepth,
    Mono,
    Legato,
    Glide,
    TremDepth,
    TremPitch,
    TremRate,
    EqLowDb,
    EqLowHz,
    EqMidDb,
    EqMidHz,
    EqMidQ,
    EqHighDb,
    EqHighHz,
    LowCut,
    HighCut,
    ChorusMix,
    ChorusRate,
    ChorusDepth,
    DriveAmount,
    DriveTone,
    DriveLevel,
    Leslie,
    SwellBox,
    Wind,
}

impl PartParam {
    pub const ALL: &'static [(&'static str, PartParam)] = &[
        ("volume", PartParam::Volume),
        ("pan", PartParam::Pan),
        ("reverbSend", PartParam::ReverbSend),
        ("brightness", PartParam::Brightness),
        ("evenHarmonics", PartParam::EvenDb),
        ("noise", PartParam::NoiseDb),
        ("attack", PartParam::AttackScale),
        ("decay", PartParam::DecayScale),
        ("release", PartParam::ReleaseScale),
        ("vibrato", PartParam::VibratoCents),
        ("vibratoRate", PartParam::VibratoRate),
        ("vibratoDelay", PartParam::VibratoDelay),
        ("naturalVibrato", PartParam::Expression),
        ("formant", PartParam::Formant),
        ("inharmonicity", PartParam::Inharmonicity),
        ("spread", PartParam::Spread),
        ("humanize", PartParam::Humanize),
        ("velocitySensitivity", PartParam::VelocitySens),
        ("maxPartials", PartParam::MaxPartials),
        ("gain", PartParam::GainDb),
        ("jitter", PartParam::Jitter),
        ("shimmer", PartParam::Shimmer),
        ("transpose", PartParam::Transpose),
        ("tune", PartParam::Tune),
        ("bendRange", PartParam::BendRange),
        ("modDepth", PartParam::ModDepth),
        ("mono", PartParam::Mono),
        ("legato", PartParam::Legato),
        ("glide", PartParam::Glide),
        ("tremolo", PartParam::TremDepth),
        ("tremoloPitch", PartParam::TremPitch),
        ("tremoloRate", PartParam::TremRate),
        ("eqLowGain", PartParam::EqLowDb),
        ("eqLowFreq", PartParam::EqLowHz),
        ("eqMidGain", PartParam::EqMidDb),
        ("eqMidFreq", PartParam::EqMidHz),
        ("eqMidQ", PartParam::EqMidQ),
        ("eqHighGain", PartParam::EqHighDb),
        ("eqHighFreq", PartParam::EqHighHz),
        ("lowCut", PartParam::LowCut),
        ("highCut", PartParam::HighCut),
        ("chorus", PartParam::ChorusMix),
        ("chorusRate", PartParam::ChorusRate),
        ("chorusDepth", PartParam::ChorusDepth),
        ("drive", PartParam::DriveAmount),
        ("driveTone", PartParam::DriveTone),
        ("driveLevel", PartParam::DriveLevel),
        ("leslie", PartParam::Leslie),
        ("swellBox", PartParam::SwellBox),
        ("wind", PartParam::Wind),
    ];

    pub fn parse(name: &str) -> Option<PartParam> {
        Self::ALL.iter().find(|(n, _)| *n == name).map(|(_, p)| *p)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MasterParam {
    Volume,
    Ceiling,
    ReverbReturn,
    ReverbDecay,
    ReverbLowMult,
    ReverbHighMult,
    ReverbSize,
    ReverbPredelay,
    ReverbDiffusion,
    ReverbEarly,
    ReverbWidth,
    ReverbLowCut,
    ReverbHighCut,
    ReverbModulation,
}

impl MasterParam {
    pub const ALL: &'static [(&'static str, MasterParam)] = &[
        ("volume", MasterParam::Volume),
        ("ceiling", MasterParam::Ceiling),
        ("reverbLevel", MasterParam::ReverbReturn),
        ("reverbDecay", MasterParam::ReverbDecay),
        ("reverbLowDecay", MasterParam::ReverbLowMult),
        ("reverbHighDecay", MasterParam::ReverbHighMult),
        ("reverbSize", MasterParam::ReverbSize),
        ("reverbPredelay", MasterParam::ReverbPredelay),
        ("reverbDiffusion", MasterParam::ReverbDiffusion),
        ("reverbEarly", MasterParam::ReverbEarly),
        ("reverbWidth", MasterParam::ReverbWidth),
        ("reverbLowCut", MasterParam::ReverbLowCut),
        ("reverbHighCut", MasterParam::ReverbHighCut),
        ("reverbModulation", MasterParam::ReverbModulation),
    ];

    pub fn parse(name: &str) -> Option<MasterParam> {
        Self::ALL.iter().find(|(n, _)| *n == name).map(|(_, p)| *p)
    }
}
