export { Synth } from './Synth.js';
export type { SynthOptions, SynthSettings, MidiPlayOptions, MidiTarget, BackendKind } from './Synth.js';
export { Instrument } from './Instrument.js';
export type { InstrumentOptions } from './Instrument.js';
export { Organ, Division } from './Organ.js';
export type { OrganOptions, OrganSettings, DivisionSettings, OrganMidiChannels, OrganMidiOptions } from './Organ.js';
export type { Playable, PlayOptions, TimeOptions, SequenceStep, SequenceOptions } from './scheduling.js';
// configurations (also importable on their own from 'supersynth/instruments' and 'supersynth/organs')
export * from './catalog/index.js';
export * from './organs/index.js';
export { PARAM_DEFAULTS } from './params.js';
export type { InstrumentParams, ReverbPreset, ReverbOptions } from './params.js';
export { noteNumber, noteName, noteFrequency, chord } from './notes.js';
export type { NoteLike } from './notes.js';
export { parseMidiFile } from './midifile.js';
export type { MidiFileData, MidiFileEvent } from './midifile.js';
export { writeWav, encodeWav } from './wav.js';
export type { AudioBuffer, WavOptions } from './wav.js';
export { AudioBackendError, MidiError, SupersynthError } from './errors.js';
export type { MidiEvent } from './types.js';
